import assert from 'node:assert/strict';
import { test } from 'node:test';
import { handle, type Services, type Store } from '../server/app.ts';
import { sourceUrl, sourcePages, safePath, newJob } from '../server/contracts.ts';
import { seal, unseal, cookie, assertMutation } from '../server/security.ts';
const SECRET='a-secure-test-only-value-012345678901234567890123456789';
const ORIGIN='https://moltick.netlify.app';
const ID='3bc27a4d-0bd2-4c1e-a688-97399545bc12';
function setup(){
  const map=new Map<string,any>();const store:Store={get:async(k)=>map.get(k)??null,setJSON:async(k,v)=>{map.set(k,structuredClone(v));},set:async(k,v)=>{map.set(k,v);},list:async({prefix})=>({blobs:[...map.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}),delete:async(k)=>{map.delete(k);}};
  const calls:any[]=[];
  const services:Services={store,env:{secret:SECRET,origin:ORIGIN,context:'production'},github:async(_t,p,init)=>{calls.push({p,init});if(p==='/user')return{login:'acts2man'};if(p.endsWith('/actions/secrets?per_page=100'))return{secrets:['OPENAI_API_KEY','MOLT_AI_MODEL','MOLT_GITHUB_EXPORT_TOKEN'].map(name=>({name}))};if(p.endsWith('/actions/workflows/reconstruct-site.yml'))return{state:'active'};if(p.includes('dispatches'))return null;if(p.includes('workflows?'))return{workflows:[]};return{permissions:{push:true}};},identifyRunner:async()=>({runId:123}),saveSecrets:async()=>{},checkProvider:async()=>{}};
  const session=seal({token:'github_pat_test_not_real_0123456789',login:'acts2man',expires:Date.now()+100000},SECRET);
  const req=(path:string,method='GET',body?:any,authenticated=true)=>new Request(ORIGIN+'/api/molt/'+path,{method,headers:{origin:ORIGIN,'x-molt-request':'1','content-type':'application/json',...(authenticated?{cookie:cookie(session)}:{})},...(body?{body:JSON.stringify(body)}:{})});
  return{map,services,calls,req};
}
test('public URLs normalize and reject credentials, scripts and private literals',()=>{assert.equal(sourceUrl('ceballostreeservices.com'),'https://ceballostreeservices.com/');for(const u of ['javascript:alert(1)','http://127.0.0.1','https://user:pass@example.com','https://a.local','https://example.com?a=1'])assert.throws(()=>sourceUrl(u));});
test('explicit pages are same-origin and deduplicated',()=>{assert.deepEqual(sourcePages('https://example.com','/\n/about\n/about#team'),['https://example.com/','https://example.com/about']);assert.throws(()=>sourcePages('https://example.com','https://evil.com'));});
test('unsafe bundle paths and executable project manifests are rejected',()=>{for(const p of ['../a.html','/a.html','.env','assets/../secret.txt','package.json','a.sh'])assert.throws(()=>safePath(p));assert.equal(safePath('images/tree.webp'),'images/tree.webp');});
test('sessions are encrypted, authenticated, owner-scoped and expiring',()=>{const original={token:'never-leak-this-token',login:'acts2man',expires:Date.now()+100000};const encoded=seal(original,SECRET);assert.ok(!encoded.includes(original.token));assert.deepEqual(unseal(encoded,SECRET),original);assert.equal(unseal(encoded.slice(1),SECRET),null);assert.equal(unseal(encoded,SECRET+'wrong'),null);assert.equal(unseal(seal({...original,expires:1},SECRET),SECRET),null);assert.equal(unseal(seal({...original,login:'other'},SECRET),SECRET),null);});
test('cookie has security attributes',()=>{for(const flag of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.ok(cookie('opaque').includes(flag));});
test('cross-origin writes are denied',()=>{assert.throws(()=>assertMutation(new Request(ORIGIN,{method:'POST',headers:{origin:'https://evil.test','x-molt-request':'1'}})));});
test('session health never returns a credential',async()=>{const s=setup();const r=await handle(s.req('session'),s.services);const text=await r.text();assert.ok(!text.includes('github_pat'));assert.equal(JSON.parse(text).connected,true);});
test('anonymous readers cannot inspect private jobs',async()=>{const s=setup();assert.equal((await handle(s.req('jobs','GET',undefined,false),s.services)).status,401);});
test('no unconfigured model can start a paid job',async()=>{const s=setup();s.services.github=async()=>({secrets:[]});const r=await handle(s.req('jobs','POST',{id:ID,url:'https://example.com',developmentTest:true}),s.services);assert.equal(r.status,409);assert.equal(s.map.size,0);});
test('output repository defaults from the source host and rejects unsafe names',()=>{assert.equal(newJob({id:ID,url:'https://www.example.com'},'acts2man').outputRepo,'example-com-react');assert.throws(()=>newJob({id:ID,url:'https://example.com',outputRepo:'../bad'},'acts2man'));});
test('dispatch calls the actual workflow and a repeated id is not resubmitted',async()=>{const s=setup();for(let i=0;i<2;i++){const r=await handle(s.req('jobs','POST',{id:ID,url:'https://example.com',developmentTest:true}),s.services);assert.ok([200,202].includes(r.status));}assert.equal(s.calls.filter(c=>c.p.includes('dispatches')).length,1);assert.equal(s.map.get('jobs/acts2man/'+ID).status,'queued');});
test('dispatch failure is not a success toast or a stuck queued record',async()=>{const s=setup(),gh=s.services.github!;s.services.github=async(t,p,i)=>{if(p.includes('dispatches'))throw new Error('failed');return gh(t,p,i);};const r=await handle(s.req('jobs','POST',{id:ID,url:'https://example.com',developmentTest:true}),s.services);assert.equal(r.status,500);assert.equal(s.map.get('jobs/acts2man/'+ID).status,'error');});
test('GitHub connection validates ownership',async()=>{const s=setup();s.services.github=async()=>({login:'other'});const r=await handle(s.req('connect','POST',{token:'github_pat_not_real_0123456789'},false),s.services);assert.equal(r.status,403);});
test('GitHub connection stores the owner token only as an encrypted Actions secret for output export',async()=>{const s=setup();let saved='';s.services.saveSecrets=async(_t,v)=>{saved=String(v.MOLT_GITHUB_EXPORT_TOKEN??'');};const r=await handle(s.req('connect','POST',{token:'github_pat_not_real_0123456789'},false),s.services);assert.equal(r.status,200);assert.equal(saved,'github_pat_not_real_0123456789');assert.ok(!(await r.text()).includes('github_pat_not_real'));});
test('settings save checks the new model credential and does not persist it in app data',async()=>{const s=setup();let checked=false,saved=false;s.services.checkProvider=async()=>{checked=true;};s.services.saveSecrets=async(_t,v)=>{saved=!!v.OPENAI_API_KEY;};const r=await handle(s.req('settings','POST',{provider:'openai',model:'model-id',apiKey:'private-test-key-0123456789012345'}),s.services);assert.equal(r.status,200);assert.ok(checked&&saved);assert.ok(!JSON.stringify([...s.map.values()]).includes('private-test-key'));assert.ok(!(await r.text()).includes('private-test-key'));});
test('unverified model credential changes nothing',async()=>{const s=setup();s.services.checkProvider=async()=>{throw new Error('bad key');};let saved=false;s.services.saveSecrets=async()=>{saved=true;};const r=await handle(s.req('settings','POST',{provider:'openai',model:'m',apiKey:'private-test-key-0123456789'}),s.services);assert.equal(r.status,500);assert.equal(saved,false);});
test('runner cannot change another workflow run',async()=>{const s=setup();s.map.set('jobs/acts2man/'+ID,{...newJob({id:ID,url:'example.com'},'acts2man'),runId:999});const r=await handle(s.req('runner/'+ID),s.services);assert.equal(r.status,409);});
test('runner data is not accepted without identity verification',async()=>{const s=setup();s.services.identifyRunner=async()=>{throw new Error('invalid identity');};const r=await handle(s.req('runner/'+ID+'/events','POST',{message:'fake'}),s.services);assert.equal(r.status,500);assert.equal(s.map.size,0);});
test('runner progress updates existing work and preserves the run identity',async()=>{const s=setup();s.map.set('jobs/acts2man/'+ID,newJob({id:ID,url:'example.com'},'acts2man'));const r=await handle(s.req('runner/'+ID+'/events','POST',{message:'Capturing desktop'}),s.services);assert.equal(r.status,200);const job=s.map.get('jobs/acts2man/'+ID);assert.equal(job.runId,123);assert.equal(job.status,'running');assert.equal(job.events.length,1);});
test('runner uploads an interactive preview and only the owner session can frame it',async()=>{
 const s=setup();s.map.set('jobs/acts2man/'+ID,newJob({id:ID,url:'example.com'},'acts2man'));
 const upload=new Request(ORIGIN+'/api/molt/runner/'+ID+'/preview?file=index.html',{method:'PUT',body:new TextEncoder().encode('<!doctype html><title>Preview</title>')});
 assert.equal((await handle(upload,s.services)).status,200);
 await handle(s.req('runner/'+ID+'/events','POST',{message:'preview ready',previewReady:true}),s.services);
 const r=await handle(s.req('preview/'+ID+'/'),s.services);
 assert.equal(r.status,200);assert.match(r.headers.get('content-type')??'',/text\\/html/);assert.equal(r.headers.get('x-frame-options'),'SAMEORIGIN');assert.match(r.headers.get('content-security-policy')??'',/frame-ancestors 'self'/);assert.match(await r.text(),/Preview/);
 assert.equal((await handle(s.req('preview/'+ID+'/','GET',undefined,false),s.services)).status,401);
});
test('image callback rejects HTML payloads',async()=>{const s=setup();s.map.set('jobs/acts2man/'+ID,newJob({id:ID,url:'example.com'},'acts2man'));const r=await handle(s.req('runner/'+ID+'/images/image.png','PUT',{html:'<script>alert(1)</script>'}),s.services);assert.equal(r.status,415);});

test('production jobs cannot use the owner development runner',async()=>{const s=setup();const r=await handle(s.req('jobs','POST',{id:ID,url:'https://example.com'}),s.services);assert.equal(r.status,400);assert.equal(s.calls.filter(c=>c.p.includes('dispatches')).length,0);});
