import { test } from 'node:test';
import assert from 'node:assert/strict';
import { usageRecord,usageSummary } from '../src/reconstruct/usage.js';
test('Astra estimate uses actual input/cache/output and does not double-count reasoning',()=>{const r=usageRecord(1,'openai','gpt-6-astra',{input_tokens:100000,input_tokens_details:{cached_tokens:20000},output_tokens:10000,output_tokens_details:{reasoning_tokens:5000}},'completed');assert.equal(r.estimatedUsd,1.32);});
test('large contexts use the documented long-context rates',()=>{const r=usageRecord(1,'openai','gpt-6-astra',{input_tokens:300000,output_tokens:10000},'completed');assert.equal(r.estimatedUsd,6.75);});
test('unreported failures and unknown model pricing are not marked free',()=>{assert.equal(usageRecord(1,'openai','gpt-6-astra',null,'transport-error').estimatedUsd,null);assert.equal(usageRecord(1,'anthropic','other',{input_tokens:10,output_tokens:10},'end_turn').estimatedUsd,null);assert.equal(usageSummary([usageRecord(1,'openai','gpt-6-astra',null,'error')]).complete,false);});
test('invalid provider usage does not fabricate a charge',()=>{for(const value of [-1,Infinity,NaN])assert.equal(usageRecord(1,'openai','gpt-6-astra',{input_tokens:value,output_tokens:10},'response').reported,false);assert.equal(usageRecord(1,'openai','gpt-6-astra',{input_tokens:10,input_tokens_details:{cached_tokens:20},output_tokens:10},'response').estimatedUsd,null);});
test('usage records never include payloads or credentials',()=>{const record=usageRecord(1,'openai','gpt-6-astra',{input_tokens:100,output_tokens:100,key:'private',prompt:'secret'},'completed');assert.ok(!JSON.stringify(record).includes('private'));assert.ok(!JSON.stringify(record).includes('secret'));});

import {createModel} from '../src/reconstruct/provider.js';
test('incomplete provider response still retains its reported usage',async()=>{const model=createModel({provider:'openai',model:'gpt-6-astra',key:'fixture-only',fetcher:async()=>new Response(JSON.stringify({status:'incomplete',usage:{input_tokens:100,output_tokens:200}}))});await assert.rejects(()=>model.complete({prompt:'test',images:[]},AbortSignal.timeout(1000)));assert.equal(model.usage.records?.length,1);assert.equal(model.usage.outputTokens,200);assert.ok(model.usage.costEstimate?.estimatedUsd);});
test('transport failure creates an unpriced usage record rather than a free result',async()=>{const model=createModel({provider:'openai',model:'gpt-6-astra',key:'fixture-only',fetcher:async()=>{throw new Error('transport unavailable');}});await assert.rejects(()=>model.complete({prompt:'test',images:[]},AbortSignal.timeout(1000)));assert.equal(model.usage.records?.[0].reported,false);assert.equal(model.usage.records?.[0].estimatedUsd,null);});
