import { useState, useEffect } from 'react';
import { Icon } from '../icons';
import { PublicFrame } from './Landing';
export const MODEL_ID='gpt-5.6-sol';
export const OPENAI_MODEL_PRESETS=[
 {id:'gpt-5.6-sol',label:'GPT-5.6 Sol',note:'Recommended default · strong quality / lower cost'},
 {id:'gpt-5.6-terra',label:'GPT-5.6 Terra',note:'Balanced cost · useful for simpler sites'},
 {id:'gpt-5.6-luna',label:'GPT-5.6 Luna',note:'Lowest cost · experimental for reconstruction'},
 {id:'gpt-6-astra',label:'GPT-6 Astra',note:'Highest capability · use for difficult sites or repairs'},
] as const;
export function OwnerSetupHelp(){return <div className="setup-instructions"><h3>Your one-time owner setup</h3><ol><li><b>Create an OpenAI project named Molt.</b> In the <a href="https://platform.openai.com/settings/organization/projects" target="_blank" rel="noreferrer">API dashboard</a>, create a separate project for these tests.</li><li><b>Enable API billing.</b> Add a payment method or prepaid credit in the <a href="https://platform.openai.com/settings/organization/billing/overview" target="_blank" rel="noreferrer">billing overview</a>. Your ChatGPT plan does not pay for API requests. Review auto-recharge and spending settings.</li><li><b>Create a project API key.</b> The key needs model-read access for our connection check and Responses API write access for reconstruction. Paste it only into the password field below.</li><li><b>Choose your reconstruction model.</b> Start with <code>gpt-5.6-sol</code> for a strong quality/cost balance. You can switch to Terra, Luna, or <code>gpt-6-astra</code> at any time. Astra is best reserved for difficult sites or stubborn repair rounds while we benchmark real results.</li><li><b>Test one homepage first.</b> Open Studio, choose Website URL, keep the one-page default, then review and start the test. Expand only after inspecting the result.</li></ol><p className="fine-print">Owner configuration only. Stripe is not required for owner mode. The planned subscription product will supply model access to customers; they should not need API keys. Model documentation checked September 17, 2026.</p></div>;}
export function SetupPath({connected,ready,onConnect,onSettings,onStart}:{connected:boolean;ready:boolean;onConnect:()=>void;onSettings:()=>void;onStart:()=>void}){return <div className="setup-path" aria-label="Owner setup progress"><button className={connected?'done':''} onClick={onConnect}><span>{connected?<Icon name="check" size={13}/>:1}</span><div><b>Authorize this Studio</b><small>{connected?'Owner account connected':'Separate from ChatGPT access'}</small></div></button><button className={ready?'done':''} onClick={onSettings}><span>{ready?<Icon name="check" size={13}/>:2}</span><div><b>Add your model key</b><small>{ready?'Configuration found':'OpenAI / Sol recommended'}</small></div></button><button onClick={onStart}><span>3</span><div><b>Test one page</b><small>Compare before expanding</small></div></button></div>;}
export function WorkflowGuide({internal=false}:{internal?:boolean}){
 const content=<><div className="public-kicker">START SMALL. SEE THE RESULT. BUILD CONFIDENCE.</div><h1>One website.<br/><em>A clear next step.</em></h1><p className="page-intro">Molt is currently an owner-only development beta. The interface is live; full reconstruction quality is still being validated. This guide separates what you can try now from what needs an additional migration.</p><div className="guidance-nav"><a href="#url-guide">Use a URL</a><a href="#file-guide">Use page files</a><a href="#results-guide">Understand results</a><a href="/migration-guide">Email, payments & hosting</a></div><div className={internal?'onboarding-grid':'public-guide-grid'}>
 <article id="url-guide" className="public-guide-card"><span className="tag">OPTION A / LIVE WEBSITE</span><h2>Paste a URL.</h2><ol><li>Open <a href="/studio">Studio</a> and choose <b>Website URL</b>. Use a public site you own or are authorized to recreate, such as <code>ceballostreeservices.com</code>.</li><li>Start with <b>Homepage test</b>. Molt visits that page at desktop, tablet, and mobile widths. For larger runs, choose navigation discovery or enter page paths such as <code>/about</code>, one per line.</li><li>Set a correction limit and review the selected scope. Confirm that API usage is billed to the configured owner account, then start.</li><li>Watch the real run status. Open the comparison when available. Inspect images, text, spacing, navigation, and all three device sizes.</li></ol><p>Login-only pages, bot challenges, search/query-driven URLs, or missing source assets can prevent capture. Navigation discovery is not a promise to find every URL on the site. Molt does not ask for your WordPress password.</p></article>
 <article id="file-guide" className="public-guide-card"><span className="tag">OPTION B / SAVED WEBSITE PAGES</span><h2>Bring the files.</h2><ol><li>Save each page from your browser as <b>Webpage, Complete</b>, or use a self-contained HTML export. Include its CSS, images, and other assets. A WordPress XML export, Elementor template JSON, database dump, PDF, or screenshot alone is not the same thing.</li><li>Place all pages and their asset folders into one folder. Keep relative paths intact: <code>home.html</code>, <code>about.html</code>, and their corresponding asset folders.</li><li>Choose <b>Saved page files</b> in Studio, enter the original website address, and select that folder. Check every page mapping: for example <code>home.html</code> becomes <code>/</code>, and <code>about.html</code> becomes <code>/about</code>.</li><li>Review and submit. The app creates the required manifest for you. Saved pages are rendered offline; remote resources that were not saved will not be fetched automatically.</li></ol><p>Current limits: 12 pages, 300 files including the manifest, 4 MB per file, and 50 MB total. Extract ZIP files first. Use public material only in this development runner. If a self-contained page exceeds 4 MB, use a complete-page export with separate assets.</p></article>
 <article id="results-guide" className="public-guide-card"><span className="tag">WHAT THE ENGINE ACTUALLY DOES</span><h2>Evidence, then code.</h2><p>Capture screenshots, text, geometry, and assets &rarr; ask the configured model to write shared React components &rarr; compile the code &rarr; render it in a browser &rarr; compare the result &rarr; attempt bounded repairs and retain the best non-regressing version.</p><p><b>Ready for review</b> means the configured checks passed, not that every interaction or business integration works. <b>Needs work</b> means differences or integrations remain. <b>Error</b> means the job stopped; inspect its message before retrying.</p><p>Desktop, tablet, and mobile images must be inspected separately. The full workflow can take minutes to tens of minutes depending on scope, model speed, and repairs. There is no universal completion-time or pixel-perfect guarantee.</p></article>
 <article className="public-guide-card"><span className="tag">WHAT YOU TAKE AWAY</span><h2>A new frontend. Not your entire business backend.</h2><p>When the job produces output, the retained React/Vite source and report appear in its downloadable artifact. This beta does not automatically publish the generated website or provide a built-in post-export AI editor.</p><p>Take the source into a developer or AI coding workflow, validate the build, reconnect forms and services, then deploy. Plugin logic, email inboxes, customers, orders, payments, logins, bookings, and SEO settings are separate migration tasks.</p><p>Font licensing and export restrictions still apply. The current downloadable artifact excludes font binaries; obtain required licensed fonts from their authorized sources.</p></article></div><div className="guide-warning"><b>Before your first run:</b> connect the owner workspace and add the model key under <a href="/connections" className="inline-reference">Connections</a>. ChatGPT's GitHub permission does not authenticate this separate website. Customers are not being asked to connect to the engine repository. Owner mode does not require Stripe; customer checkout and paid plan enforcement stay disabled until the customer-facing launch.</div><a className="public-button primary" href="/studio">Open the studio <Icon name="arrow" size={17}/></a></>;
 return internal?<section className="internal-guide public-inner">{content}</section>:<PublicFrame><main id="public-main" className="public-inner">{content}</main></PublicFrame>;
}
const INTEGRATIONS=[
 ['Website hosting','Eligible static React frontends can use Netlify or another host with a free tier. Keep a buildable backup and test every route before changing DNS.','Free is subject to plan limits; functions, traffic, builds, domains and storage may add costs.'],
 ['Email inboxes','Keep the current inbox service, or migrate mail and aliases to a mailbox provider before removing the old host. Preserve MX, SPF, DKIM and DMARC records.','Resend is an application-email API, not a drop-in Gmail or Outlook inbox replacement. Do not point your root MX records elsewhere without a mailbox plan.'],
 ['Forms & notifications','Use Netlify Forms or a secured backend plus Resend for enquiry emails and notifications. Add spam controls, validation, an explicit sender domain, and a real delivery test.','Netlify email integrations also use an external email provider. Seeing a form on the page does not mean submission works.'],
 ['Commerce & payments','Choose a merchant backend and checkout, such as a server-created Stripe Checkout flow or an existing commerce platform. Keep each client business as the merchant on its own account.','Products, orders, subscriptions, customer consent, tax, shipping, refunds and historical data do not migrate from a screenshot. Do not copy payment-card data.'],
 ['Molt subscriptions','Bill for Molt itself through a separate subscription integration and credit ledger. Grant monthly credits after verified payment, reserve before a job, then settle or release exactly once.','Molt subscription billing is separate from payment processing on a reconstructed client website. Customer billing is not yet live.'],
 ['Content & SEO','Inventory page URLs, titles, descriptions, canonicals, sitemaps and redirect requirements. Select a CMS or editing workflow when ongoing content changes are needed.','A public-page crawl cannot recover drafts, database records, private plugin settings or all metadata. Validate redirects and search indexing before launch.'],
 ['Members & bookings','Retain the existing provider initially or perform a separate authenticated data migration into the chosen service. Test the real login, permissions, booking and notification flows.','Authentication, memberships, access rules, recurring bookings and private data require an explicit migration plan.'],
] as const;
export function MigrationGuide(){return <PublicFrame><main id="public-main" className="public-inner"><div className="public-kicker">A SAFE EXIT, NOT A BLIND LEAP</div><h1>Move your website.<br/><em>Keep your business connected.</em></h1><p className="page-intro">Reconstructing the frontend is one part of migration. This is the service-by-service checklist to review before cancelling your WordPress hosting or changing a client's domain.</p><div className="integration-table">{INTEGRATIONS.map(([title,body,note])=><article className="integration-entry" key={title}><h3>{title}</h3><p>{body}</p><small>{note}</small></article>)}</div><div className="guide-warning"><b>Cancellation gate:</b> verified backups, working new site, working inboxes, real form-delivery test, real payment test where applicable, preserved routes and DNS, client approval, and a rollback plan. Do not cancel a domain registration just because you are cancelling web hosting.</div><h2>Keep a local migration checklist</h2><Checklist/><p className="fine-print">Documentation: <a href="https://docs.netlify.com/manage/accounts-and-billing/billing/billing-for-credit-based-plans/credit-based-pricing-plans/" target="_blank" rel="noreferrer" className="inline-reference">Netlify plan limits</a> &middot; <a href="https://resend.com/docs/dashboard/receiving/custom-domains" target="_blank" rel="noreferrer" className="inline-reference">Resend and existing MX records</a> &middot; <a href="https://docs.stripe.com/payments/checkout" target="_blank" rel="noreferrer" className="inline-reference">Stripe Checkout</a>. Reviewed September 17, 2026.</p></main></PublicFrame>;}
const CHECKS=[['backup','Backup and rollback','Keep a complete WordPress/database backup and document how to return traffic to it.'],['visual','Website and device review','Compare the design, text, imagery, page routes, and meaningful interactions on all three device sizes.'],['email','Mailbox and DNS continuity','Identify who hosts each inbox. Test incoming and outgoing email without changing existing MX records prematurely.'],['forms','Form delivery','Submit a real authorised test and confirm delivery, error handling and spam protection.'],['payments','Payments and other services','Test checkout, orders, bookings, member login and notifications where used; mark not applicable only after review.'],['seo','Routes and indexing','Review redirects, canonicals, metadata, robots rules, sitemap, analytics and ownership-verification records.'],['launch','Launch approval','Obtain approval, point the domain to the new site, monitor it, and only then decide which old services can be cancelled.']];
function Checklist(){const[checked,setChecked]=useState<string[]>([]),[note,setNote]=useState('Saved only in this browser. Checking a box does not perform or verify the migration.');useEffect(()=>{try{const a=JSON.parse(localStorage.getItem('molt-migration-checklist')??'[]');if(Array.isArray(a))setChecked(a.filter(v=>typeof v==='string'&&CHECKS.some(c=>c[0]===v)));}catch{}},[]);function change(id:string){const next=checked.includes(id)?checked.filter(x=>x!==id):[...checked,id];setChecked(next);try{localStorage.setItem('molt-migration-checklist',JSON.stringify(next));}catch{setNote('Browser storage unavailable. These selections will not persist.');}}return <><p className="readiness-note">{checked.length} of {CHECKS.length} checked &middot; {note}</p><div className="migration-checklist">{CHECKS.map(([id,title,text])=><label key={id} className="migration-check"><input type="checkbox" checked={checked.includes(id)} onChange={()=>change(id)}/><span><b>{title}</b><small>{text}</small></span></label>)}</div></>;}
