import { CreditPlanner } from './Landing';
import type { Job } from '../../server/contracts';
export function UsagePage({jobs,connected}:{jobs:Job[];connected:boolean}){
 const recorded=jobs.filter(j=>j.report?.usage||j.usage);
 const input=recorded.reduce((n,j)=>n+((j.report?.usage??j.usage).inputTokens??0),0),output=recorded.reduce((n,j)=>n+((j.report?.usage??j.usage).outputTokens??0),0),calls=recorded.reduce((n,j)=>n+((j.report?.usage??j.usage).calls??0),0),estimated=recorded.reduce((n,j)=>n+((j.report?.usage??j.usage).costEstimate?.estimatedUsd??0),0),priced=recorded.filter(j=>(j.report?.usage??j.usage).costEstimate?.complete).length;
 return <><header className="page-title"><div className="eyebrow">KNOW THE SCOPE BEFORE THE SPEND</div><h1>Usage, without the guesswork.</h1><p>Owner beta telemetry and a preview of the credit model. No customer subscription or Molt credit wallet is active.</p></header><div className="owner-explainer"><h3>API usage is not the same as Molt credits.</h3><p>Your OpenAI account pays for actual model requests. Proposed Molt credits describe a customer's reconstruction scope. They are not OpenAI tokens, Netlify credits, or dollars. Rejected model responses and repairs can still incur provider usage.</p></div><div className="usage-summary"><div><small>Reported model calls</small><strong>{connected?calls.toLocaleString():'--'}</strong><p>Retained reports, including reported failures.</p></div><div><small>Reported input tokens</small><strong>{connected?input.toLocaleString():'--'}</strong><p>Source evidence and requests, not page counts.</p></div><div><small>Reported output tokens</small><strong>{connected?output.toLocaleString():'--'}</strong><p>Provider-reported output, including applicable reasoning usage.</p></div><div><small>Estimated API spend</small><strong>{connected?'<p className="readiness-note">{connected?`${recorded.length} jobs with reports in the retrieved history.`:'Connect the owner workspace to read recorded usage.'} Missing or unfinished reports are not zero-cost proof. Use the provider dashboard for authoritative account charges.</p>{recorded.length>0&&<section className="panel issues-panel"><h2>Reported per-job usage</h2>{recorded.map(j=>{const u=j.report?.usage??j.usage;return <div className="wizard-summary" key={j.id}><div><dt>{j.name}</dt><dd>{u.records?.[0]?.model??'Unknown model'} · {u.calls??0} calls / {u.costEstimate?.estimatedUsd!=null?'~</div><small className="fine-print">{u.costEstimate?.complete?'All retained call records were priced.':'Some usage may be missing or unpriced.'} Estimates exclude compute, storage, regional/priority adjustments and taxes; the provider invoice is authoritative.</small></div>;})}</section>}<h2>Preview a project estimate</h2><CreditPlanner/><p className="readiness-note">Planning only. Complexity is self-selected, not detected. In the customer product, a measured server-side assessment must generate a versioned quote before any credits are reserved.</p><a href="/plans" className="text-button">See proposed plans and examples &rarr;</a></>;
}
+estimated.toFixed(2):'--'}</strong><p>{priced} fully priced job{priced===1?'':'s'} in retained history.</p></div></div><p className="readiness-note">{connected?`${recorded.length} jobs with reports in the retrieved history.`:'Connect the owner workspace to read recorded usage.'} Missing or unfinished reports are not zero-cost proof. Use the provider dashboard for authoritative account charges.</p>{recorded.length>0&&<section className="panel issues-panel"><h2>Reported per-job usage</h2>{recorded.map(j=>{const u=j.report?.usage??j.usage;return <div className="wizard-summary" key={j.id}><div><dt>{j.name}</dt><dd>{u.calls??0} calls / {u.costEstimate?.estimatedUsd!=null?'~$'+u.costEstimate.estimatedUsd.toFixed(2)+' API estimate':'No price estimate'}</dd></div><small className="fine-print">{u.costEstimate?.complete?'All retained call records were priced.':'Some usage may be missing or unpriced.'} Estimates exclude compute, storage, regional/priority adjustments and taxes; the provider invoice is authoritative.</small></div>;})}</section>}<h2>Preview a project estimate</h2><CreditPlanner/><p className="readiness-note">Planning only. Complexity is self-selected, not detected. In the customer product, a measured server-side assessment must generate a versioned quote before any credits are reserved.</p><a href="/plans" className="text-button">See proposed plans and examples &rarr;</a></>;
}
+u.costEstimate.estimatedUsd.toFixed(2)+' API estimate':'No price estimate'}</dd></div><small className="fine-print">{u.costEstimate?.complete?'All retained call records were priced.':'Some usage may be missing or unpriced.'} Estimates exclude compute, storage, regional/priority adjustments and taxes; the provider invoice is authoritative.</small></div>;})}</section>}<h2>Preview a project estimate</h2><CreditPlanner/><p className="readiness-note">Planning only. Complexity is self-selected, not detected. In the customer product, a measured server-side assessment must generate a versioned quote before any credits are reserved.</p><a href="/plans" className="text-button">See proposed plans and examples &rarr;</a></>;
}
+estimated.toFixed(2):'--'}</strong><p>{priced} fully priced job{priced===1?'':'s'} in retained history.</p></div></div><p className="readiness-note">{connected?`${recorded.length} jobs with reports in the retrieved history.`:'Connect the owner workspace to read recorded usage.'} Missing or unfinished reports are not zero-cost proof. Use the provider dashboard for authoritative account charges.</p>{recorded.length>0&&<section className="panel issues-panel"><h2>Reported per-job usage</h2>{recorded.map(j=>{const u=j.report?.usage??j.usage;return <div className="wizard-summary" key={j.id}><div><dt>{j.name}</dt><dd>{u.calls??0} calls / {u.costEstimate?.estimatedUsd!=null?'~$'+u.costEstimate.estimatedUsd.toFixed(2)+' API estimate':'No price estimate'}</dd></div><small className="fine-print">{u.costEstimate?.complete?'All retained call records were priced.':'Some usage may be missing or unpriced.'} Estimates exclude compute, storage, regional/priority adjustments and taxes; the provider invoice is authoritative.</small></div>;})}</section>}<h2>Preview a project estimate</h2><CreditPlanner/><p className="readiness-note">Planning only. Complexity is self-selected, not detected. In the customer product, a measured server-side assessment must generate a versioned quote before any credits are reserved.</p><a href="/plans" className="text-button">See proposed plans and examples &rarr;</a></>;
}
