import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Icon, Mark } from './icons';
import { active, api, date, label, post } from './api';
import type { Job } from '../server/contracts';

type Session={connected:boolean;login:string|null;serverReady:boolean;repository:string;branch:string};
type Settings={provider:string;model:string;keyPresent:boolean;modelConfigured:boolean;workflow:boolean;permissionsError:string;ready:boolean;configuredAt:string|null;accessChecked:boolean};
function Notice({children,tone='error'}:{children:ReactNode;tone?:string}){return <div className={`notice ${tone}`} role={tone==='error'?'alert':'status'}><Icon name="info" size={17}/><div>{children}</div></div>;}
function Pill({status}:{status:string}){return <span className={`pill ${status}`}><i/>{label(status)}</span>;}
function Empty({title,children,icon='layers'}:{title:string;children:ReactNode;icon?:string}){return <div className="empty"><span className="empty-icon"><Icon name={icon} size={26}/></span><h3>{title}</h3><p>{children}</p></div>;}
function Field({label:caption,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{caption}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function Logo(){return <div className="logo"><Mark/><div><strong>molt<span>®</span></strong><small>RECONSTRUCTION STUDIO</small></div></div>;}
function useLocation(){const [path,set]=useState(location.pathname);useEffect(()=>{const fn=()=>set(location.pathname);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn);},[]);const go=useCallback((p:string)=>{history.pushState({},'',p);set(p);window.scrollTo(0,0);},[]);return[path,go] as const;}
function useResource<T>(path:string|null,refresh:number,interval=0){
  const[data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{if(!path){setData(null);setError('');return;}let live=true,timer:ReturnType<typeof setTimeout>;const controller=new AbortController();
    const load=async()=>{setLoading(true);try{const d=await api<T>(path,{signal:controller.signal});if(live){setData(d);setError('');}}catch(e){if(live&&!controller.signal.aborted)setError((e as Error).message);}finally{if(live){setLoading(false);if(interval)timer=setTimeout(()=>{if(document.visibilityState==='visible')void load();else timer=setTimeout(()=>void load(),interval);},interval);}}};void load();return()=>{live=false;controller.abort();clearTimeout(timer);};},[path,refresh,interval]);
  return{data,error,loading};
}
export function App(){
  const[path,go]=useLocation(),[refresh,setRefresh]=useState(0),[session,setSession]=useState<Session|null>(null),[sessionError,setSessionError]=useState(''),[connect,setConnect]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState('');
  const update=()=>setRefresh(v=>v+1);
  useEffect(()=>{let live=true;api<Session>('session').then(s=>{if(live){setSession(s);setSessionError('');}}).catch(e=>{if(live)setSessionError(e.message);});return()=>{live=false;};},[refresh]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t);},[toast]);
  const jobId=path.startsWith('/studio/jobs/')?path.split('/').pop():null;
  const jobs=useResource<{jobs:Job[]}>(session?.connected?'jobs':null,refresh,jobId?0:15000);
  const settings=useResource<Settings>(session?.connected?'settings':null,refresh);
  const nav=(p:string)=>{go(p);setMenu(false);};
  const routes=[{path:'/',title:'Studio',icon:'studio'},{path:'/activity',title:'Run activity',icon:'activity'},{path:'/connections',title:'Connections',icon:'settings'}];
  return <div className="app-shell">
    <a className="skip-link" href="#main">Skip to workspace</a>
    {menu&&<button className="nav-scrim" onClick={()=>setMenu(false)} aria-label="Close navigation"/>}
    <aside className={`sidebar ${menu?'open':''}`}>
      <a className="brand-link" href="/" onClick={e=>{e.preventDefault();nav('/');}} aria-label="Molt Studio home"><Logo/></a>
      <div className="workspace-switch"><span className="workspace-avatar">RG</span><div><b>Reputation Guardians</b><small>Private reconstruction workspace</small></div><Icon name="chevron" size={15}/></div>
      <p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{routes.map(item=><a key={item.path} href={item.path} onClick={e=>{e.preventDefault();nav(item.path);}} className={(path===item.path||item.path==='/'&&!!jobId)?'selected':''} aria-current={(path===item.path)?'page':undefined}><Icon name={item.icon}/><span>{item.title}</span>{item.path==='/connections'&&!settings.data?.ready&&<span className="nav-dot"/>}</a>)}</nav>
      <div className="sidebar-foot"><div className="stack-caption"><span className="stack-line"/><b>One studio. Your code.</b><p>Built for thoughtful, evidence-led reconstruction.</p><a href="/guide" onClick={e=>{e.preventDefault();nav('/guide');}}>Inside the workflow <Icon name="arrow" size={15}/></a></div><button className="profile" onClick={()=>session?.connected?nav('/connections'):setConnect(true)}><span className="avatar">{session?.login?'TJ':'M'}</span><span><b>{session?.login??'Your workspace'}</b><small>{session?.connected?'GitHub connected':'Connect to begin'}</small></span><Icon name={session?.connected?'check':'key'} size={17}/></button></div>
    </aside>
    <div className="main-wrap">
      <header className="topbar"><div className="crumb"><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation" aria-expanded={menu}><Icon name="menu"/></button><span>Workspace</span><Icon name="chevron" size={12}/><b>{jobId?'Reconstruction':path==='/connections'?'Connections':path==='/activity'?'Run activity':path==='/guide'?'The workflow':'Studio'}</b></div><div className="top-actions"><span className={`connection-label ${session?.connected?'connected':''}`}><i/>{session?.connected?'GitHub connected':'Setup required'}</span><button className="button compact outline" onClick={()=>session?.connected?nav('/connections'):setConnect(true)}><Icon name={session?.connected?'settings':'github'} size={16}/>{session?.connected?'Workspace settings':'Connect GitHub'}</button></div></header>
      <main id="main" className={jobId?'content detail-content':'content'}>
        {sessionError&&<Notice>{sessionError} <button className="text-button" onClick={update}>Retry connection</button></Notice>}
        {session&&!session.serverReady&&<Notice>Server-side session encryption needs configuration before sign-in. The interface is available, but private job controls are locked.</Notice>}
        {jobId?<Detail id={jobId} connected={!!session?.connected} onConnect={()=>setConnect(true)} onBack={()=>nav('/')} onToast={setToast}/>:path==='/connections'?<Connections session={session} settings={settings.data} error={settings.error} onConnect={()=>setConnect(true)} onRefresh={update} onToast={setToast}/>:path==='/activity'?<Activity connected={!!session?.connected} refresh={refresh} onRefresh={update} onConnect={()=>setConnect(true)}/>:path==='/guide'?<Guide/>:path!=='/'?<Empty title="This view isn’t here." icon="globe"><button className="text-button" onClick={()=>nav('/')}>Return to the studio</button></Empty>:<>
          <section className="studio-hero"><div><div className="eyebrow"><span/>A NEW CHAPTER FOR YOUR WEBSITE</div><h1>Keep the look.<br/><em>Change what’s underneath.</em></h1><p>A considered way to turn an existing website into editable React.<br className="desktop-break"/> Capture the details. Compare the result. Refine the difference.</p></div><div className="hero-art" aria-hidden="true"><div className="art-orbit"/><div className="art-window reference"><div className="art-window-head"><i/><i/><i/></div><div className="art-body"><div className="art-title"/><div className="art-line"/><div className="art-line short"/><div className="art-grid"><i/><i/><i/></div></div><span>REFERENCE</span></div><div className="art-window rebuilt"><div className="art-window-head"><Icon name="code" size={14}/><b>React</b></div><div className="art-body"><div className="art-code">{'<YourWebsite>'}</div><div className="art-line"/><div className="art-line short"/><div className="art-code">{'</YourWebsite>'}</div></div><span>EDITABLE SOURCE</span></div><div className="art-link"><Icon name="arrow" size={20}/></div></div></section>
          <div className="workflow-strip">{[{n:'01',title:'Capture',text:'The original, in detail',icon:'globe'},{n:'02',title:'Reconstruct',text:'React, with measured refinement',icon:'code'},{n:'03',title:'Review',text:'Evidence beside the result',icon:'layers'}].map(s=><div key={s.n}><span className="step-number">{s.n}</span><Icon name={s.icon} size={18}/><span><b>{s.title}</b><small>{s.text}</small></span><Icon name="arrow" size={15}/></div>)}</div>
          <div className="creation-grid"><NewReconstruction ready={!!settings.data?.ready} connected={!!session?.connected} onConnect={()=>setConnect(true)} onSettings={()=>nav('/connections')} onCreated={id=>{update();nav(`/studio/jobs/${id}`);}}/><aside className="run-spec"><div className="eyebrow">BUILT DIFFERENTLY</div><h2>Not a screenshot.<br/>A real starting point.</h2><p>The engine writes React source, builds it, and checks it against the reference before it asks you to review.</p><div className="spec-row"><Icon name="monitor"/><span>Three perspectives<b>Desktop · Tablet · Mobile</b></span></div><div className="spec-row"><Icon name="code"/><span>Your code, not a wrapper<b>React + responsive CSS</b></span></div><div className="spec-row"><Icon name="shield"/><span>Evidence over promises<b>Unresolved differences stay visible</b></span></div><div className="spec-foot"><span className="tiny-mark">m</span><span>Hosted on Netlify.<br/>Jobs run on GitHub Actions.</span></div></aside></div>
          <section className="projects-section"><div className="section-heading"><div><div className="eyebrow">YOUR WORK</div><h2>Recent reconstructions <span className="count">{jobs.data?.jobs.length??0}</span></h2></div><button className="text-button" onClick={update} disabled={jobs.loading}><Icon name="refresh" size={15}/>Refresh</button></div>{jobs.error?<Notice>{jobs.error}</Notice>:jobs.loading&&!jobs.data?<div className="loading-state">Loading your workspace…</div>:!jobs.data?.jobs.length?<Empty title={session?.connected?'Your first reconstruction starts here.':'A clear home for every reconstruction.'}>{session?.connected?'Start with a website above. Its captures, progress, and review will appear here.':'Connect your GitHub workspace to start a run and see its actual progress here.'}</Empty>:<div className="project-list">{jobs.data.jobs.slice(0,8).map(j=><button className="project-row" key={j.id} onClick={()=>nav(`/studio/jobs/${j.id}`)}><span className="project-monogram">{j.name[0].toUpperCase()}</span><span className="project-info"><b>{j.name}</b><small>{j.bundleId?'Saved page bundle':'Live website'} <i>·</i> {date(j.createdAt)}</small></span><Pill status={j.status}/><Icon name="arrow" size={19}/></button>)}</div>}</section>
        </>}
        <footer className="workspace-footer"><span>MOLT STUDIO <i>/</i> RECONSTRUCTION, WITH INTENTION.</span><span>acts2man/molt.tick <i>·</i> Netlify</span></footer>
      </main>
    </div>
    {connect&&<ConnectDialog serverReady={!!session?.serverReady} onClose={()=>setConnect(false)} onConnected={()=>{setConnect(false);update();setToast('GitHub connected. Your private workspace is ready.');}}/>}
    {toast&&<div className="toast" role="status"><Icon name="check" size={18}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><Icon name="close" size={15}/></button></div>}
  </div>;
}
function ConnectDialog({serverReady,onClose,onConnected}:{serverReady:boolean;onClose:()=>void;onConnected:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await post('connect',{token});setToken('');onConnected();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <dialog ref={dialog} className="dialog" onCancel={onClose} onClick={e=>{if(e.target===dialog.current&&!busy)onClose();}}><div className="dialog-inner"><button className="dialog-close icon-button" onClick={onClose} aria-label="Close connection dialog"><Icon name="close"/></button><span className="connection-icon"><Icon name="github" size={28}/></span><div className="eyebrow">ONE SECURE CONNECTION</div><h2>Bring your workspace<br/>into the studio.</h2><p>Molt uses your GitHub account to start runs and retrieve their results. This workspace belongs to <b>acts2man</b>.</p><div className="permissions"><b>Create a fine-grained GitHub token</b><span>Repository access: <code>acts2man/molt.tick</code></span><div><span>Actions <strong>Read & write</strong></span><span>Secrets <strong>Read & write</strong></span><span>Contents <strong>Read-only</strong></span></div><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">Open GitHub token settings <Icon name="external" size={14}/></a></div><form onSubmit={submit}><Field label="GitHub access token"><input autoFocus type="password" autoComplete="off" placeholder="github_pat_…" value={token} onChange={e=>setToken(e.target.value)} required minLength={20}/></Field>{error&&<Notice>{error}</Notice>}<button className="button primary full" disabled={busy||!serverReady}>{busy?'Verifying your connection…':'Connect workspace'}<Icon name="arrow" size={17}/></button></form><p className="security-note"><Icon name="shield" size={15}/>Encrypted, HttpOnly session. Never stored in browser local storage. Disconnect at any time; sessions expire after eight hours.</p></div></dialog>;
}
function NewReconstruction({ready,connected,onConnect,onSettings,onCreated}:{ready:boolean;connected:boolean;onConnect:()=>void;onSettings:()=>void;onCreated:(id:string)=>void}){
  const [mode,setMode]=useState<'url'|'files'>('url'),[url,setUrl]=useState('https://ceballostreeservices.com'),[pages,setPages]=useState(''),[maxPages,setMaxPages]=useState(5),[repairs,setRepairs]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [files,setFiles]=useState<{file:File;path:string}[]>([]),[mapping,setMapping]=useState<{file:string;route:string}[]>([]);
  const idRef=useRef<string|null>(null),inputRef=useRef<HTMLInputElement>(null);
  async function selectFiles(list:FileList|null){if(!list)return;setError('');const selected=Array.from(list).map(file=>({file,path:(file.webkitRelativePath||file.name).replace(/^[^/]+\//,'')})).filter(f=>/\.(html?|css|js|png|jpe?g|svg|webp|gif|avif|ico|woff2?|ttf|otf)$/i.test(f.path));
    if(selected.some(f=>f.file.size>4_000_000)||selected.reduce((n,f)=>n+f.file.size,0)>49_000_000||selected.length>299){setError('Use up to 299 files, each under 4 MB, and 49 MB total. Larger sites can use the engine CLI.');return;}
    const html=selected.filter(f=>/\.html?$/i.test(f.path));if(!html.length||html.length>12){setError('Choose a folder containing 1–12 saved HTML pages and their assets.');return;}
    setFiles(selected);setMapping(html.map((f,i)=>({file:f.path,route:/^(index|home)\.html?$/i.test(f.path)?'/':i===0&&html.length===1?'/':'/'+f.path.replace(/\.html?$/i,'').replace(/[^a-zA-Z0-9/-]/g,'-').toLowerCase()})));setMaxPages(Math.max(5,html.length));idRef.current=null;
  }
  async function submit(e:FormEvent){e.preventDefault();if(!connected){onConnect();return;}if(!ready){onSettings();return;}setError('');setBusy(true);setMessage('Preparing reconstruction…');
    try{let normalized:string;try{normalized=new URL(/^https?:\/\//i.test(url)?url:`https://${url}`).href;}catch{throw new Error('Enter a valid website address.');}
      let bundleId:string|undefined;
      if(mode==='files'){
        if(!files.length)throw new Error('Choose a saved-page folder first.');if(new Set(mapping.map(m=>m.route)).size!==mapping.length)throw new Error('Each saved page needs a unique route.');
        const manifest=new File([JSON.stringify({site:normalized,pages:mapping})],'bundle.json',{type:'application/json'}),upload=[...files,{file:manifest,path:'bundle.json'}];
        const bundle=await post('bundles',{files:upload.map(f=>({path:f.path,size:f.file.size}))});bundleId=bundle.id;
        for(let i=0;i<upload.length;i++){setMessage(`Uploading ${i+1} of ${upload.length} files…`);await api(`bundles/${bundleId}?file=${encodeURIComponent(upload[i].path)}`,{method:'PUT',body:upload[i].file,headers:{'content-type':'application/octet-stream'}});}
        await post(`bundles/${bundleId}/complete`);
      }
      setMessage('Starting the real engine…');const id=idRef.current??crypto.randomUUID();idRef.current=id;
      const job=await post('jobs',{id,url:normalized,pages:mode==='url'?pages:'',maxPages,maxRepairs:repairs,bundleId});idRef.current=null;onCreated(job.id);
    }catch(e){setError((e as Error).message);}finally{setBusy(false);setMessage('');}
  }
  return <section className="source-card"><div className="card-head"><div><span className="eyebrow">START SOMETHING</span><h2>New reconstruction</h2></div><span className="card-corner"><Icon name="plus" size={22}/></span></div><div className="source-tabs" role="tablist" aria-label="Input method"><button type="button" role="tab" aria-selected={mode==='url'} onClick={()=>setMode('url')}><Icon name="globe" size={17}/>Website URL</button><button type="button" role="tab" aria-selected={mode==='files'} onClick={()=>setMode('files')}><Icon name="upload" size={17}/>Saved page files</button></div><form onSubmit={submit}><Field label={mode==='url'?'Which website are we rebuilding?':'Original website address'} hint={mode==='url'?'Use a public website you own or have permission to recreate.':'Used to preserve original page and link relationships.'}><div className="input-with-icon"><Icon name="globe" size={19}/><input value={url} onChange={e=>{setUrl(e.target.value);idRef.current=null;}} required placeholder="https://your-website.com" autoComplete="url" aria-label="Website address"/></div></Field>
    {mode==='files'&&<><input ref={inputRef} type="file" multiple {...({webkitdirectory:''} as any)} className="visually-hidden" onChange={e=>void selectFiles(e.target.files)} aria-label="Select saved page folder"/><button type="button" className="upload-zone" onClick={()=>inputRef.current?.click()}><Icon name="folder" size={26}/><b>{files.length?`${files.length} files selected`:'Choose a saved-page folder'}</b><span>HTML pages, styles, and images · up to 49 MB</span></button>{!!mapping.length&&<div className="page-mapping">{mapping.map((m,i)=><label key={m.file}><span title={m.file}>{m.file}</span><input aria-label={`Route for ${m.file}`} value={m.route} onChange={e=>setMapping(mapping.map((p,n)=>n===i?{...p,route:e.target.value}:p))}/></label>)}</div>}</>}
    <div className="form-options"><Field label="Page limit"><select value={maxPages} onChange={e=>setMaxPages(Number(e.target.value))}>{[1,2,3,5,8,10,12].map(n=><option key={n} value={n}>{n} {n===1?'page':'pages'}</option>)}</select></Field><Field label="Refinement budget"><select value={repairs} onChange={e=>setRepairs(Number(e.target.value))}>{[0,1,2,3,4,6].map(n=><option key={n} value={n}>{n===0?'First pass only':`${n} correction rounds`}</option>)}</select></Field></div>
    {mode==='url'&&<details className="advanced"><summary>Choose specific pages <span>Optional</span></summary><Field label="Page paths, one per line" hint="Leave blank to discover navigation links, up to your page limit."><textarea rows={4} placeholder={'/\n/about\n/services'} value={pages} onChange={e=>setPages(e.target.value)}/></Field></details>}
    <div className="capture-sizes"><span>CAPTURE AT</span><span><Icon name="monitor" size={15}/>1440</span><span><Icon name="tablet" size={15}/>768</span><span><Icon name="mobile" size={15}/>390</span><b>px</b></div>
    {error&&<Notice>{error}</Notice>}{!ready&&<div className="setup-note"><span className="status-dot"/><span>{connected?'Add your model connection to enable the engine.':'Connect your workspace once to enable real reconstruction jobs.'}</span></div>}
    <button className="button primary full start-button" disabled={busy}>{busy?message:!connected?'Connect workspace to begin':!ready?'Set up model connection':'Start reconstruction'}<Icon name={busy?'clock':'arrow'} size={19}/></button><p className="cost-note">You stay in control: bounded pages and repairs. API and runner usage may apply. This public engine repository is for public website material—not confidential uploads.</p></form></section>;
}
function Connections({session,settings,error,onConnect,onRefresh,onToast}:{session:Session|null;settings:Settings|null;error:string;onConnect:()=>void;onRefresh:()=>void;onToast:(s:string)=>void}){
  const [provider,setProvider]=useState('openai'),[model,setModel]=useState(''),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[problem,setProblem]=useState('');
  useEffect(()=>{if(settings){setProvider(settings.provider);setModel(settings.model);}},[settings]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setProblem('');try{await post('settings',{provider,model,apiKey:key});setKey('');onRefresh();onToast('Model settings saved to GitHub. Your API key was not returned to the browser.');}catch(e){setProblem((e as Error).message);}finally{setBusy(false);}}
  async function disconnect(){try{await post('disconnect');onRefresh();onToast('Workspace disconnected.');}catch(e){setProblem((e as Error).message);}}
  return <><PageTitle eyebrow="CONNECTED, NOT COMPLICATED" title="Your studio, configured." description="A clear view of where the app runs, where the work happens, and what the engine can use."/>{error&&<Notice>{error}</Notice>}<div className="connections-grid"><section className="panel connection-card"><div className="connection-top"><span className="connection-icon"><Icon name="github" size={25}/></span><Pill status={session?.connected?'review':'pending'}/></div><h2>GitHub workspace</h2><p>Source code, reconstruction runners, and encrypted model credentials—all in the repository you already own.</p><dl><div><dt>Repository</dt><dd>acts2man/molt.tick</dd></div><div><dt>Execution branch</dt><dd>main</dd></div><div><dt>Signed in as</dt><dd>{session?.login??'Not connected'}</dd></div></dl><button className="button outline full" onClick={session?.connected?disconnect:onConnect}>{session?.connected?'Disconnect this session':'Connect GitHub'}<Icon name={session?.connected?'close':'arrow'} size={17}/></button><small className="fine-print">Owner-only access. Sessions expire after eight hours; reconnecting does not delete jobs.</small></section>
      <section className="panel connection-card model-card"><div className="connection-top"><span className="connection-icon"><Icon name="code" size={25}/></span><span className={`pill ${settings?.ready?'review':'pending'}`}><i/>{settings?.ready?'Configured':'Connection needed'}</span></div><h2>The reconstruction model</h2><p>Select an image-capable API model. The engine sends it visual evidence and asks for measured, targeted refinements.</p><form onSubmit={save}><div className="form-options"><Field label="Provider"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></Field><Field label="Exact API model ID"><input required value={model} onChange={e=>setModel(e.target.value)} placeholder="Your available model ID" autoComplete="off"/></Field></div><Field label={settings?.keyPresent?'API key · already stored':'API key'} hint="Saved encrypted in GitHub Actions Secrets, not in source code or browser storage."><input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={settings?.keyPresent?'Leave blank to keep the existing key':'Enter your provider API key'} required={!settings?.keyPresent}/></Field>{problem&&<Notice>{problem}</Notice>}{settings?.permissionsError&&<Notice>{settings.permissionsError} Your GitHub token needs repository Secrets read and write permission.</Notice>}<button className="button primary full" disabled={!session?.connected||busy}>{busy?'Verifying and saving…':'Check and save connection'}<Icon name="shield" size={17}/></button></form><small className="fine-print">A new key is checked for model access before saving. API billing is separate from a chat subscription. Model image support is validated during reconstruction.</small></section>
      <section className="panel hosting-card"><div><span className="eyebrow">ALREADY IN PLACE</span><h2>No Railway required.</h2><p>Netlify serves this interface and its private API. GitHub Actions starts an isolated runner for each job. There is no additional always-on application server.</p></div><div className="hosting-items"><div><Icon name="globe"/><span><b>Netlify</b><small>{session?.serverReady?'Interface + private API available':'Interface available · session setup needed'}</small></span><Icon name={session?.serverReady?'check':'info'} size={18}/></div><div><Icon name="github"/><span><b>GitHub Actions</b><small>{settings?.workflow?'Reconstruction workflow found':session?.connected?'Checking workflow configuration':'Connect GitHub to verify the runner'}</small></span><Icon name={settings?.workflow?'check':'info'} size={18}/></div></div></section></div></>;
}
function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <header className="page-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></header>;}
function Activity({connected,refresh,onRefresh,onConnect}:{connected:boolean;refresh:number;onRefresh:()=>void;onConnect:()=>void}){
  const {data,error,loading}=useResource<{runs:any[]}>(connected?'activity':null,refresh,20000),[filter,setFilter]=useState('all');const rows=data?.runs.filter(r=>filter==='all'||(filter==='engine'?r.name!=='Engine checks'&&r.name!=='Studio checks':r.name.includes('checks')))??[];
  return <><PageTitle eyebrow="A VISIBLE PROCESS" title="Nothing behind the curtain." description="Actual workflow runs, with their recorded status and logs. A green test is not a completed website reconstruction."/><div className="section-heading"><div className="filter-buttons">{['all','engine','checks'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f==='all'?'All activity':f==='engine'?'Reconstruction':'Build checks'}</button>)}</div><button className="text-button" onClick={onRefresh} disabled={loading}><Icon name="refresh" size={15}/>Refresh</button></div>{error?<Notice>{error}</Notice>:!connected?<Empty title="Connect to see the actual activity." icon="activity"><button className="text-button" onClick={onConnect}>Connect GitHub <Icon name="arrow" size={15}/></button></Empty>:!data?<div className="loading-state">Reading GitHub Actions…</div>:!rows.length?<Empty title="No matching runs yet.">New workflow runs will appear here.</Empty>:<div className="activity-list">{rows.map(r=><a className="activity-row" key={r.id} href={r.url} target="_blank" rel="noreferrer"><span className={`activity-symbol ${r.conclusion==='success'?'success':r.conclusion==='failure'?'failure':''}`}><Icon name={r.conclusion==='success'?'check':r.status==='completed'?'info':'clock'} size={18}/></span><span><b>{r.name}</b><small>{r.title}</small><small>{date(r.createdAt)} <i>·</i> {r.branch} <i>·</i> {r.commit}</small></span><span className="activity-status">{r.conclusion??r.status}</span><Icon name="external" size={16}/></a>)}</div>}</>;
}
function Detail({id,connected,onConnect,onBack,onToast}:{id:string;connected:boolean;onConnect:()=>void;onBack:()=>void;onToast:(s:string)=>void}){
  const[refresh,setRefresh]=useState(0),[route,setRoute]=useState(''),[viewport,setViewport]=useState('desktop'),[diff,setDiff]=useState(false),[cancelBusy,setCancelBusy]=useState(false);
  const{data:job,error,loading}=useResource<Job&{artifacts:any[]}>(connected?`jobs/${id}`:null,refresh,5000);
  const views=job?.report?.evaluation?.views??[],routes:string[]=Array.from(new Set(views.map((v:any)=>String(v.route))));
  const selected=views.find((v:any)=>v.route===(route||routes[0])&&v.viewport===viewport);
  const image=(name:string)=>`/api/molt/jobs/${id}/images/${name}`;
  async function cancel(){if(!confirm('Stop this reconstruction? The runner will be asked to cancel. Completed evidence remains available.'))return;setCancelBusy(true);try{await post(`jobs/${id}/cancel`);setRefresh(n=>n+1);onToast('Cancellation requested.');}catch(e){onToast((e as Error).message);}finally{setCancelBusy(false);}}
  if(!connected)return <Empty title="This reconstruction belongs to your workspace."><button className="text-button" onClick={onConnect}>Connect GitHub to open it</button></Empty>;
  if(error)return <Notice>{error} <button className="text-button" onClick={()=>setRefresh(n=>n+1)}>Retry</button></Notice>;
  if(!job)return <div className="loading-state">Opening the reconstruction…</div>;
  return <><button className="text-button back" onClick={onBack}><Icon name="arrow" size={15} style={{transform:'rotate(180deg)'}}/>All reconstructions</button><div className="detail-header"><div><div className="eyebrow">RECONSTRUCTION WORKSPACE</div><h1>{job.name}</h1><p>{job.bundleId?'Saved-page bundle':'Live website'} <i>·</i> {date(job.createdAt)}</p></div><div className="detail-actions"><Pill status={job.status}/>{active(job.status)&&<button className="button outline compact" disabled={cancelBusy||job.status==='cancelling'} onClick={cancel}>Stop run</button>}</div></div><div className="run-message"><span className={active(job.status)?'pulse-dot':'status-dot'}/><span>{job.message}</span>{loading&&<Icon name="refresh" size={14}/>}</div>
    {job.error&&<Notice>{job.error}</Notice>}
    {!job.report?<div className="in-progress-grid"><div className="panel processing-panel"><div className="processing-glyph"><Icon name={active(job.status)?'layers':'info'} size={40}/></div><div className="eyebrow">{active(job.status)?'THE ENGINE IS WORKING':'RUN DETAILS'}</div><h2>{active(job.status)?'A rebuild worth looking closely at.':'This run needs attention.'}</h2><p>{active(job.status)?'The runner captures the source, builds React, and measures each device size. Its real progress appears alongside this view.':'No completed React report was received. The timeline and GitHub logs show where the run stopped.'}</p><div className="processing-devices"><Icon name="monitor" size={25}/><Icon name="tablet" size={22}/><Icon name="mobile" size={18}/></div></div><Timeline job={job}/></div>:<>
      <div className="review-toolbar"><div><Icon name="layers" size={18}/><select aria-label="Page to review" value={route||routes[0]||''} onChange={e=>setRoute(e.target.value)}>{routes.map(r=><option key={r} value={r}>{r}</option>)}</select></div><div className="device-tabs" role="group" aria-label="Review viewport">{['desktop','tablet','mobile'].map(v=><button key={v} onClick={()=>setViewport(v)} className={v===viewport?'selected':''} aria-pressed={v===viewport}><Icon name={v==='desktop'?'monitor':v} size={17}/><span>{v}</span></button>)}</div><button className={`button compact ${diff?'primary':'outline'}`} onClick={()=>setDiff(!diff)} aria-pressed={diff}>Difference map</button></div>
      {selected?<><div className="comparison"><div className="comparison-pane"><header><b>Original reference</b><span>{viewport}</span></header><div className="comparison-scroll">{selected.sourceImage?<img src={image(selected.sourceImage)} alt={`Original ${selected.route} at ${viewport} size`}/>:<Empty title="Source image unavailable.">The runner did not upload this preview.</Empty>}</div></div><div className="comparison-pane"><header><b>{diff?'Measured differences':'Reconstructed React'}</b><span className="metric">{typeof selected.score==='number'?`${selected.score.toFixed(1)}% pixel match`:'Not measured'}</span></header><div className="comparison-scroll">{(diff?selected.diffImage:selected.candidateImage)?<img src={image(diff?selected.diffImage:selected.candidateImage)} alt={diff?'Pixel difference map':`React reconstruction of ${selected.route}`}/>:<Empty title="No generated image yet.">The original is never substituted for a missing React result.</Empty>}</div></div></div><div className="comparison-note"><Icon name="info" size={15}/>Pixel similarity is one measurement, not a guarantee of functionality. Preview images may be scaled for the studio.</div>{!!selected.issues?.length&&<section className="panel issues-panel"><h3>Differences to resolve</h3>{selected.issues.map((s:string,i:number)=><p key={i}><span/>{s}</p>)}</section>}</>:<Empty title="No measurement for this view.">Choose another page or device.</Empty>}
      {!!job.report.blockers?.length&&<section className="panel issues-panel"><h3>Integration decisions</h3><p>These are not repaired by acknowledging them. Forms, media, and other services need an actual connection.</p>{job.report.blockers.map((s:string,i:number)=><p key={i}><Icon name="info" size={14}/>{s}</p>)}</section>}
      <div className="in-progress-grid"><Timeline job={job}/><section className="panel handoff"><div className="eyebrow">THE WORK IS YOURS</div><h2>Review. Then move forward.</h2><p>Open the run logs or retrieve the actual saved artifacts. Nothing is automatically published over your original website.</p>{job.artifacts?.map((a:any)=><a className="button outline full" key={a.name} href={a.url} target="_blank" rel="noreferrer"><Icon name="download" size={17}/>{a.name}<Icon name="external" size={14}/></a>)}{!job.artifacts?.length&&<small>Artifacts appear after the runner finishes and uploads them.</small>}<div className="usage-summary"><span>Model calls<b>{job.report.usage?.calls??0}</b></span><span>Input tokens<b>{(job.report.usage?.inputTokens??0).toLocaleString()}</b></span><span>Output tokens<b>{(job.report.usage?.outputTokens??0).toLocaleString()}</b></span></div><small>Artifacts on GitHub have limited retention and require GitHub access. Token counts are usage, not a cost estimate.</small></section></div>
    </>}</>;
}
function Timeline({job}:{job:Job}){return <section className="panel timeline"><div className="section-heading"><h3>Run timeline</h3>{job.runUrl&&<a className="text-button" href={job.runUrl} target="_blank" rel="noreferrer">Full logs<Icon name="external" size={13}/></a>}</div><div className="timeline-events">{job.events.length?job.events.map((e,i)=><div key={i}><span className="timeline-dot"/><div><small>{date(e.at)}</small><p>{e.message}</p></div></div>):<p className="muted">Waiting for the runner’s first progress event. This is not simulated progress.</p>}</div></section>;}
function Guide(){return <><PageTitle eyebrow="INTELLIGENCE, MADE VISIBLE" title="A reconstruction. Not a guess." description="The original is the reference—not a suggestion to redesign. Here’s what happens after you press start."/><div className="guide-grid">{[{n:'01',title:'Read the actual website',text:'The browser collects screenshots, visible content, assets, and geometry at desktop, tablet, and mobile widths. Saved-page folders are opened without external network access.'},{n:'02',title:'Build something you can own',text:'An image-capable model authors real React components and responsive styling. Shared elements can be reused. Captured WordPress HTML is evidence, never the finished app.'},{n:'03',title:'Look at what was built',text:'Molt compiles the React project and measures its rendered pages against the reference. Missing text, mismatched layout, failed images, and pixel differences stay visible.'},{n:'04',title:'Refine without going backwards',text:'The engine asks for targeted repairs within your selected budget. Changes that regress other measured views are rolled back. The best measured implementation is retained.'},{n:'05',title:'Make the final call',text:'Review the result by page and device. Open the source files and the actual run logs. A passed visual threshold does not claim that forms, checkout, authentication, or animations have been fully migrated.'}].map(s=><section className="panel guide-card" key={s.n}><span>{s.n}</span><div><h2>{s.title}</h2><p>{s.text}</p></div></section>)}</div><Notice tone="neutral">This studio runs the engine in <b>acts2man/molt.tick</b>. Netlify hosts the interface; GitHub Actions supplies the job runner. No Railway connection is required. Provider API and hosting usage allowances still apply.</Notice></>;
}
