import { spawn } from 'node:child_process';
import { appendFile, readFile } from 'node:fs/promises';

export interface PublishResult { url:string; repository:string }

function validRepo(name:string):string{
  const value=name.trim().toLowerCase();
  if(!/^[a-z0-9](?:[a-z0-9._-]{0,98}[a-z0-9])?$/.test(value)||value.includes('..'))throw new Error('Invalid output repository name');
  return value;
}
async function run(command:string,args:string[],cwd:string,env:Record<string,string|undefined>={}):Promise<string>{
  return await new Promise((resolve,reject)=>{
    const child=spawn(command,args,{cwd,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});
    let out='',err='';
    child.stdout.on('data',b=>{if(out.length<12000)out+=String(b);});
    child.stderr.on('data',b=>{if(err.length<12000)err+=String(b);});
    child.on('error',reject);
    child.on('close',code=>code===0?resolve(out.trim()):reject(new Error(`${command} failed (exit ${code}): ${(err||out).trim().slice(0,1200)}`)));
  });
}
async function exists(owner:string,repo:string,token:string,cwd:string):Promise<boolean>{
  try{await run('gh',['repo','view',`${owner}/${repo}`,'--json','name'],cwd,{GH_TOKEN:token});return true;}catch{return false;}
}
export async function publishOutputRepository(directory:string,owner:string,name:string,token:string):Promise<PublishResult>{
  const requested=validRepo(name);
  if(!token||token.length<20)throw new Error('GitHub export token is missing. Reconnect Molt with repository creation permissions.');
  let repo=requested;
  if(await exists(owner,repo,token,directory)){
    let found='';
    for(let version=2;version<=30;version++){const candidate=validRepo(`${requested}-v${version}`);if(!(await exists(owner,candidate,token,directory))){found=candidate;break;}}
    if(!found)throw new Error(`Could not find an available GitHub repository name after ${owner}/${requested}-v30.`);
    repo=found;
  }
  const ignore='\n# Molt excludes font binaries from generated repositories\n*.woff\n*.woff2\n*.ttf\n*.otf\nnode_modules/\ndist/\n';
  await appendFile(`${directory}/.gitignore`,ignore);
  const readmePath=`${directory}/README.md`;
  let readme='';try{readme=await readFile(readmePath,'utf8');}catch{}
  if(!readme.includes('Generated by Molt'))await appendFile(readmePath,`\n\n---\nGenerated by Molt from an authorized website reconstruction. Review integrations, forms, payments, authentication, email, and licensing before production use.\n`);
  await run('git',['init','-b','main'],directory);
  await run('git',['config','user.name','Molt Reconstruction'],directory);
  await run('git',['config','user.email','molt@users.noreply.github.com'],directory);
  await run('git',['add','.'],directory);
  await run('git',['commit','-m','Initial React reconstruction from Molt'],directory);
  await run('gh',['repo','create',`${owner}/${repo}`,'--private','--source',directory,'--remote','origin','--push','--description','React reconstruction generated by Molt'],directory,{GH_TOKEN:token});
  return {repository:`${owner}/${repo}`,url:`https://github.com/${owner}/${repo}`};
}
