import { spawn } from 'node:child_process';
import { appendFile, readFile } from 'node:fs/promises';

export interface PublishResult { url:string; repository:string }

function validRepo(name:string):string{
  const value=name.trim().toLowerCase();
  if(!/^[a-z0-9](?:[a-z0-9._-]{0,98}[a-z0-9])?$/.test(value)||value.includes('..'))throw new Error('Invalid output repository name');
  return value;
}
async function run(command:string,args:string[],cwd:string,env:Record<string,string|undefined>={}):Promise<string>{
  return await new Promise((resolve,reject)=>{
    const child=spawn(command,args,{cwd,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});
    let out='',err='';
    child.stdout.on('data',b=>{if(out.length<12000)out+=String(b);});
    child.stderr.on('data',b=>{if(err.length<12000)err+=String(b);});
    child.on('error',reject);
    child.on('close',code=>code===0?resolve(out.trim()):reject(new Error(`${command} failed (exit ${code}): ${(err||out).trim().slice(0,1200)}`)));
  });
}
async function exists(owner:string,repo:string,token:string,cwd:string):Promise<boolean>{
  try{await run('gh',['repo','view',`${owner}/${repo}`,'--json','name'],cwd,{GH_TOKEN:token});return true;}catch{return false;}
}
export async function reserveOutputRepository(directory:string,owner:string,name:string,token:string):Promise<PublishResult>{
  const requested=validRepo(name);
  if(!token||token.length<20)throw new Error('GitHub export token is missing. Reconnect Molt with repository creation permissions.');
  const login=await run('gh',['api','user','--jq','.login'],directory,{GH_TOKEN:token});
  if(login.trim().toLowerCase()!==owner.toLowerCase())throw new Error(`GitHub export token belongs to ${login||'another account'}, not ${owner}.`);
  await run('gh',['repo','view','acts2man/molt.tick','--json','name'],directory,{GH_TOKEN:token});
  let repo=requested;
  if(await exists(owner,repo,token,directory)){
    let found='';
    for(let version=2;version<=30;version++){const candidate=validRepo(`${requested}-v${version}`);if(!(await exists(owner,candidate,token,directory))){found=candidate;break;}}
    if(!found)throw new Error(`Could not find an available GitHub repository name after ${owner}/${requested}-v30.`);
    repo=found;
  }
  const repository=`${owner}/${repo}`;
  await run('gh',['repo','create',repository,'--private','--add-readme','--description','React reconstruction reserved by Molt'],directory,{GH_TOKEN:token});
  try{
    // Prove the *new* repository accepts the exact privileged operations the post-model handoff needs.
    await run('gh',['secret','set','MOLT_HANDOFF_PREFLIGHT','--repo',repository,'--body','verified'],directory,{GH_TOKEN:token});
    await run('gh',['secret','delete','MOLT_HANDOFF_PREFLIGHT','--repo',repository],directory,{GH_TOKEN:token});
    const probe=`name: Molt handoff permission probe
on:
  workflow_dispatch:
jobs:
  permission-check:
    if: \${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo permission-check
`;
    const encoded=Buffer.from(probe,'utf8').toString('base64');
    const sha=await run('gh',['api',`repos/${repository}/contents/.github/workflows/molt-permission-check.yml`,'--method','PUT','--field','message=Verify Molt workflow permission','--field',`content=${encoded}`,'--jq','.content.sha'],directory,{GH_TOKEN:token});
    await run('gh',['api',`repos/${repository}/contents/.github/workflows/molt-permission-check.yml`,'--method','DELETE','--field','message=Remove Molt workflow permission probe','--field',`sha=${sha.trim()}`],directory,{GH_TOKEN:token});
  }catch(error){
    try{await run('gh',['repo','delete',repository,'--yes'],directory,{GH_TOKEN:token});}catch{}
    throw new Error('GitHub delivery preflight failed before model usage: '+(error instanceof Error?error.message:String(error)));
  }
  return {repository,url:`https://github.com/${repository}`};
}
export async function publishReservedOutputRepository(directory:string,repository:string,token:string):Promise<PublishResult>{
  if(!token||token.length<20)throw new Error('GitHub export token is missing.');
  if(!/^acts2man\/[a-z0-9][a-z0-9._-]{0,99}$/i.test(repository))throw new Error('Invalid reserved output repository.');
  const ignore='\n# Generated repository hygiene\nnode_modules/\ndist/\n';
  await appendFile(`${directory}/.gitignore`,ignore);
  const readmePath=`${directory}/README.md`;
  let readme='';try{readme=await readFile(readmePath,'utf8');}catch{}
  if(!readme.includes('Generated by Molt'))await appendFile(readmePath,'\n\n---\nGenerated by Molt from an authorized website reconstruction. Review integrations, forms, payments, authentication, email, and licensing before production use.\n');
  await run('git',['init','-b','main'],directory);
  await run('git',['config','user.name','Molt Reconstruction'],directory);
  await run('git',['config','user.email','molt@users.noreply.github.com'],directory);
  await run('git',['add','.'],directory);
  await run('git',['commit','-m','Initial React reconstruction from Molt'],directory);
  await run('git',['remote','add','origin',`https://github.com/${repository}.git`],directory);
  await run('git',['push','-u','--force','origin','main'],directory,{GH_TOKEN:token,GIT_CONFIG_COUNT:'1',GIT_CONFIG_KEY_0:'http.https://github.com/.extraheader',GIT_CONFIG_VALUE_0:`AUTHORIZATION: basic ${Buffer.from('x-access-token:'+token).toString('base64')}`});
  return {repository,url:`https://github.com/${repository}`};
}
