/**
 * Molt Stage 6 — Ship.
 *
 * Pushes the faithful reproduction into a Lovable project's GitHub repo so the
 * migrated site shows up in Lovable (which two-way-syncs its `main` branch).
 *
 * Clean approach: Molt's pages + CSS + a router that points at them REPLACE
 * Lovable's starter content, while we leave Lovable's scaffolding (package.json,
 * vite.config, tailwind, etc.) untouched so the project still builds and syncs.
 *
 * Uses the GitHub Contents API with a fine-grained PAT (env GITHUB_TOKEN,
 * Contents: read+write on the target repo). Pushes to `main` — Lovable only
 * syncs the default branch.
 */

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, relative } from 'node:path';

const GH = 'https://api.github.com';

export interface ShipOptions {
  repo: string;           // "owner/name"
  outDir: string;         // the faithful project dir (has src/pages, src/html, src/styles, src/main.tsx)
  token?: string;         // defaults to env GITHUB_TOKEN
  branch?: string;        // defaults to the repo's default branch
  commitMessage?: string;
}

export interface ShipResult {
  pushed: boolean;
  filesPushed: number;
  commit?: string;
  branch: string;
  error?: string;
}

async function gh(token: string, path: string, init?: RequestInit): Promise<any> {
  const res = await fetch(`${GH}${path}`, {
    ...init,
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`GitHub ${res.status} on ${path}: ${body.message ?? JSON.stringify(body)}`);
  return body;
}

/** Recursively collect files under a dir as { path (repo-relative), content }. */
async function collectFiles(root: string, sub = ''): Promise<{ path: string; content: Buffer }[]> {
  const out: { path: string; content: Buffer }[] = [];
  const dir = join(root, sub);
  for (const name of await readdir(dir)) {
    if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'renders') continue;
    const full = join(dir, name);
    const st = await stat(full);
    if (st.isDirectory()) {
      out.push(...await collectFiles(root, join(sub, name)));
    } else {
      out.push({ path: relative(root, full).replace(/\\/g, '/'), content: await readFile(full) });
    }
  }
  return out;
}

/**
 * Which faithful files do we push into the Lovable repo? Only our CONTENT —
 * pages, their raw HTML, and their CSS — plus a router (src/App.tsx) pointing at
 * them. We deliberately DON'T push our package.json / vite.config / index.html /
 * main.tsx, so Lovable's own scaffolding stays intact and keeps building.
 */
function isShippableFaithfulFile(p: string): boolean {
  return p.startsWith('src/pages/')
    || p.startsWith('src/html/')
    || p.startsWith('src/styles/');
}

/** Build the Lovable-compatible App.tsx that routes to the pushed faithful pages. */
function buildAppTsx(routes: { route: string; comp: string; file: string }[]): string {
  const imports = routes.map((r) => `import ${r.comp} from "./pages/${r.file}";`).join('\n');
  const routeEls = routes.map((r) => `        <Route path=${JSON.stringify(r.route)} element={<${r.comp} />} />`).join('\n');
  return `import { BrowserRouter, Routes, Route } from "react-router-dom";
${imports}

// Generated by Molt — faithful visual reproduction. Edit freely in Lovable.
export default function App() {
  return (
    <BrowserRouter>
      <Routes>
${routeEls}
      </Routes>
    </BrowserRouter>
  );
}
`;
}

export async function shipToLovable(opts: ShipOptions): Promise<ShipResult> {
  const token = opts.token ?? process.env.GITHUB_TOKEN;
  if (!token) return { pushed: false, filesPushed: 0, branch: '', error: 'GITHUB_TOKEN not set' };
  const [owner, name] = opts.repo.split('/');
  if (!owner || !name) return { pushed: false, filesPushed: 0, branch: '', error: `bad repo "${opts.repo}" (want owner/name)` };

  try {
    // 1. resolve branch + its current tip commit + tree
    const repoInfo = await gh(token, `/repos/${owner}/${name}`);
    const branch = opts.branch ?? repoInfo.default_branch ?? 'main';
    const ref = await gh(token, `/repos/${owner}/${name}/git/ref/heads/${branch}`);
    const baseCommitSha = ref.object.sha;
    const baseCommit = await gh(token, `/repos/${owner}/${name}/git/commits/${baseCommitSha}`);
    const baseTreeSha = baseCommit.tree.sha;

    // 2. gather faithful content files + read routing metadata
    const all = await collectFiles(opts.outDir);
    const shippable = all.filter((f) => isShippableFaithfulFile(f.path));
    const molt = JSON.parse((all.find((f) => f.path === 'MOLT_OUTPUT.json')?.content ?? Buffer.from('{}')).toString());
    const routeList: string[] = molt.routes ?? [];
    const routeMeta = routeList.map((route) => ({
      route,
      comp: route === '/' ? 'Home' : route.slice(1).split(/[-/]/).map((s) => (s[0]?.toUpperCase() ?? '') + s.slice(1)).join('') || 'Page',
      file: route === '/' ? 'index' : route.slice(1).replace(/\/$/, '').replace(/\//g, '.'),
    }));

    // 3. create blobs for every file (base64 so binary-safe)
    const treeItems: { path: string; mode: '100644'; type: 'blob'; sha: string }[] = [];
    for (const f of shippable) {
      const blob = await gh(token, `/repos/${owner}/${name}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content: f.content.toString('base64'), encoding: 'base64' }),
      });
      treeItems.push({ path: f.path, mode: '100644', type: 'blob', sha: blob.sha });
    }
    // the router that ties the pages together
    const appBlob = await gh(token, `/repos/${owner}/${name}/git/blobs`, {
      method: 'POST',
      body: JSON.stringify({ content: Buffer.from(buildAppTsx(routeMeta)).toString('base64'), encoding: 'base64' }),
    });
    treeItems.push({ path: 'src/App.tsx', mode: '100644', type: 'blob', sha: appBlob.sha });

    // 4. new tree on top of the existing one (only our files change; rest untouched)
    const newTree = await gh(token, `/repos/${owner}/${name}/git/trees`, {
      method: 'POST',
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
    });

    // 5. commit + move branch
    const commit = await gh(token, `/repos/${owner}/${name}/git/commits`, {
      method: 'POST',
      body: JSON.stringify({
        message: opts.commitMessage ?? 'Molt — faithful migration',
        tree: newTree.sha,
        parents: [baseCommitSha],
      }),
    });
    await gh(token, `/repos/${owner}/${name}/git/refs/heads/${branch}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: false }),
    });

    return { pushed: true, filesPushed: treeItems.length, commit: commit.sha, branch };
  } catch (e) {
    return { pushed: false, filesPushed: 0, branch: opts.branch ?? 'main', error: (e as Error).message };
  }
}
