/**
 * Molt Stage 6 — Ship.
 *
 * Pushes the faithful reproduction into a Lovable project's GitHub repo so the
 * migrated site shows up in Lovable (which two-way-syncs its `main` branch).
 *
 * Clean approach: Molt's pages + CSS + a router that points at them REPLACE
 * Lovable's starter content, while we leave Lovable's scaffolding (package.json,
 * vite.config, tailwind, etc.) untouched so the project still builds and syncs.
 *
 * Uses the GitHub Contents API with a fine-grained PAT (env GITHUB_TOKEN,
 * Contents: read+write on the target repo). Pushes to `main` — Lovable only
 * syncs the default branch.
 */

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, relative } from 'node:path';

const GH = 'https://api.github.com';

export interface ShipOptions {
  repo: string;           // "owner/name"
  outDir: string;         // the faithful project dir (has src/pages, src/html, src/styles, src/main.tsx)
  token?: string;         // defaults to env GITHUB_TOKEN
  branch?: string;        // defaults to the repo's default branch
  commitMessage?: string;
}

export interface ShipResult {
  pushed: boolean;
  filesPushed: number;
  commit?: string;
  branch: string;
  error?: string;
}

async function gh(token: string, path: string, init?: RequestInit): Promise<any> {
  const res = await fetch(`${GH}${path}`, {
    ...init,
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(init?.headers ?? {}),
    },
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`GitHub ${res.status} on ${path}: ${body.message ?? JSON.stringify(body)}`);
  return body;
}

/** Recursively collect files under a dir as { path (repo-relative), content }. */
async function collectFiles(root: string, sub = ''): Promise<{ path: string; content: Buffer }[]> {
  const out: { path: string; content: Buffer }[] = [];
  const dir = join(root, sub);
  for (const name of await readdir(dir)) {
    if (name === 'node_modules' || name === '.git' || name === 'dist' || name === 'renders') continue;
    const full = join(dir, name);
    const st = await stat(full);
    if (st.isDirectory()) {
      out.push(...await collectFiles(root, join(sub, name)));
    } else {
      out.push({ path: relative(root, full).replace(/\\/g, '/'), content: await readFile(full) });
    }
  }
  return out;
}

/**
 * Which faithful files do we push into the Lovable repo? Only our CONTENT —
 * the raw HTML and the CSS. The route WIRING we generate fresh as TanStack
 * Router files (src/routes/*), because Lovable projects use TanStack Router,
 * not react-router-dom. We DON'T push our package.json / vite.config / main.tsx.
 */
function isShippableFaithfulFile(p: string): boolean {
  return p.startsWith('src/html/')
    || p.startsWith('src/styles/');
}

/** TanStack Router file name for a route: '/' → index, '/about' → about, '/a/b' → a.b */
function tanstackRouteFile(route: string): string {
  return route === '/' ? 'index' : route.slice(1).replace(/\/$/, '').replace(/\//g, '.');
}

/** Build a TanStack Router route file that renders the faithful page. */
function buildRouteFile(route: string, slug: string, bodyClass: string): string {
  const importPath = tanstackRouteFile(route);
  return `import { createFileRoute } from '@tanstack/react-router';
import html from '../html/${slug}.html?raw';
import '../styles/${slug}.css';

// Faithful visual reproduction of ${route} — generated by Molt. Edit freely.
function MoltPage() {
  return <div className=${JSON.stringify(bodyClass)} dangerouslySetInnerHTML={{ __html: html }} />;
}

export const Route = createFileRoute('${route}')({ component: MoltPage });
`;
}

export async function shipToLovable(opts: ShipOptions): Promise<ShipResult> {
  const token = opts.token ?? process.env.GITHUB_TOKEN;
  if (!token) return { pushed: false, filesPushed: 0, branch: '', error: 'GITHUB_TOKEN not set' };
  const [owner, name] = opts.repo.split('/');
  if (!owner || !name) return { pushed: false, filesPushed: 0, branch: '', error: `bad repo "${opts.repo}" (want owner/name)` };

  try {
    // 1. resolve branch + its current tip commit + tree
    const repoInfo = await gh(token, `/repos/${owner}/${name}`);
    const branch = opts.branch ?? repoInfo.default_branch ?? 'main';
    const ref = await gh(token, `/repos/${owner}/${name}/git/ref/heads/${branch}`);
    const baseCommitSha = ref.object.sha;
    const baseCommit = await gh(token, `/repos/${owner}/${name}/git/commits/${baseCommitSha}`);
    const baseTreeSha = baseCommit.tree.sha;

    // 2. gather faithful content files (html + css) + read routing metadata
    const all = await collectFiles(opts.outDir);
    const shippable = all.filter((f) => isShippableFaithfulFile(f.path));
    const molt = JSON.parse((all.find((f) => f.path === 'MOLT_OUTPUT.json')?.content ?? Buffer.from('{}')).toString());
    const pageInfo: { route: string; slug: string; bodyClass: string }[] = molt.pages ?? [];

    // 3. create blobs for every content file (base64 so binary-safe)
    const treeItems: { path: string; mode: '100644'; type: 'blob'; sha: string }[] = [];
    for (const f of shippable) {
      const blob = await gh(token, `/repos/${owner}/${name}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content: f.content.toString('base64'), encoding: 'base64' }),
      });
      treeItems.push({ path: f.path, mode: '100644', type: 'blob', sha: blob.sha });
    }
    // TanStack Router route files (src/routes/*) — the wiring Lovable expects
    for (const pg of pageInfo) {
      const routeSrc = buildRouteFile(pg.route, pg.slug, pg.bodyClass);
      const routeBlob = await gh(token, `/repos/${owner}/${name}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content: Buffer.from(routeSrc).toString('base64'), encoding: 'base64' }),
      });
      treeItems.push({ path: `src/routes/${tanstackRouteFile(pg.route)}.tsx`, mode: '100644', type: 'blob', sha: routeBlob.sha });
    }

    // 4. new tree on top of the existing one (only our files change; rest untouched)
    const newTree = await gh(token, `/repos/${owner}/${name}/git/trees`, {
      method: 'POST',
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
    });

    // 5. commit + move branch
    const commit = await gh(token, `/repos/${owner}/${name}/git/commits`, {
      method: 'POST',
      body: JSON.stringify({
        message: opts.commitMessage ?? 'Molt — faithful migration',
        tree: newTree.sha,
        parents: [baseCommitSha],
      }),
    });
    await gh(token, `/repos/${owner}/${name}/git/refs/heads/${branch}`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: false }),
    });

    return { pushed: true, filesPushed: treeItems.length, commit: commit.sha, branch };
  } catch (e) {
    return { pushed: false, filesPushed: 0, branch: opts.branch ?? 'main', error: (e as Error).message };
  }
}
